version = 1

[[runtimes]]
name = "ruby"
version = "3.2.0+20230118-8aec06d"
status = "active"
args = [ "--", "/src/index.rb" ]
binary = "https://github.com/vmware-labs/webassembly-language-runtimes/releases/download/ruby%2F3.2.0%2B20230118-8aec06d/ruby-3.2.0.wasm"
binary_checksum = "e2d91cff05ec59ed9c88aadbd3b477842092054bf24c5d944d5ad6dbafdd3b32"
extensions = [ "rb" ]
polyfill = "https://raw.githubusercontent.com/Angelmmiguel/wws-index-test/main/ruby/poly.rb"
polyfill_checksum = "2ba09117ed20a05480615b2aaaf6c7cd7f61fa06f4919777d773df2fcbc736cf"
template = "https://raw.githubusercontent.com/Angelmmiguel/wws-index-test/main/ruby/template.txt"
template_checksum = "6d808b4747cf30f82665a38a47e1176513bbdd6ad558c09db03d719e33ad2da0"
