version = 1

[[runtimes]]
name = "ruby"
version = "3.2.0"
status = "active"
args = [ "--", "/src/index.rb" ]
binary = { url = "https://github.com/Angelmmiguel/wws-index-test/releases/download/preview/ruby-3.2.0-full.wasm", filename = "ruby.wasm", checksum = { type = "sha256", value = "23641ef154fee1fba4bb156c01642b3ebc0f46eb0eebe66502d979f64a114f31" } }
extensions = [ "rb" ]
polyfill = { url = "https://raw.githubusercontent.com/Angelmmiguel/wws-index-test/main/ruby/poly.rb", filename = "poly.rb", checksum = { type = "sha256", value = "2ba09117ed20a05480615b2aaaf6c7cd7f61fa06f4919777d773df2fcbc736cf" } }
wrapper = { url = "https://raw.githubusercontent.com/Angelmmiguel/wws-index-test/main/ruby/template.txt", filename = "template.txt", checksum = { type = "sha256", value = "6d808b4747cf30f82665a38a47e1176513bbdd6ad558c09db03d719e33ad2da0" } }
